'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),toast=document.querySelector('#toast');
const W=1100,H=620,world=2400,keys=new Set();
const platforms=[{x:0,y:520,w:410,h:100},{x:490,y:460,w:180,h:160},{x:730,y:405,w:180,h:215},{x:980,y:500,w:320,h:120},{x:1480,y:470,w:260,h:150},{x:1810,y:410,w:170,h:210},{x:2050,y:490,w:350,h:130}];
const bridge={x:1300,y:500,w:180,h:24},switchPad={x:820,y:405,w:64},starSeeds=[{x:570,y:416},{x:1585,y:420},{x:1900,y:355}];
let spaceHeld=0;
const HOLD_THRESHOLD=.22;
let body,head,joined,active,angle,charge,charging,camera,checkpoint,stars,won,bridgeOpen,mergeDelay,time=0,last=0,pointer=null,particles=[];
function say(s){toast.textContent=s}
function entity(x,y,w,h){return{x,y,w,h,vx:0,vy:0,ground:false}}
function reset(full=true){if(full){checkpoint=0;stars=starSeeds.map(s=>({...s,got:false}));won=false;bridgeOpen=false}body=entity(checkpoint?1040:100,checkpoint?468:488,30,32);head=entity(body.x+1,body.y-28,28,28);joined=true;active='body';angle=-Math.PI/4;charge=0;charging=false;spaceHeld=0;camera=Math.max(0,body.x-220);mergeDelay=0;pointer=null;say(full?'把头抛向远方，再一起回家。':'回到检查点，再试一次！')}
reset();
function controlled(){return joined||active==='body'?body:head}
function overlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function launch(){if(!joined||won)return;const force=380+charge*620;joined=false;active='head';head.vx=Math.cos(angle)*force;head.vy=Math.sin(angle)*force;head.ground=false;mergeDelay=.45;charging=false;charge=0;say('头部出发！按 Tab 切换身体，相碰即可合体。')}
function jump(){const p=controlled();if(p.ground&&!won){p.vy=joined?-470:active==='head'?-480:-365;p.ground=false}}
window.addEventListener('keydown',e=>{if(['Space','Tab','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='Tab'&&!joined){active=active==='body'?'head':'body';say(active==='body'?'正在控制身体':'正在控制头部')}if(e.code==='KeyR')reset(false);if(e.code==='Space'&&!won){if(joined){charging=true;charge=0;spaceHeld=0}else jump()}});
window.addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='Space'&&charging){if(spaceHeld<HOLD_THRESHOLD){charging=false;charge=0;jump()}else launch();spaceHeld=0}});
window.addEventListener('blur',()=>{keys.clear();charging=false;charge=0;spaceHeld=0;last=0});
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();pointer={x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height}});document.querySelector('#restart').onclick=()=>reset();
function physics(p,dt,move){const speed=p===head?225:245;if(move){const dir=Number(keys.has('KeyD')||keys.has('ArrowRight'))-Number(keys.has('KeyA')||keys.has('ArrowLeft'));p.vx+=dir*1500*dt;if(dir)p.vx=Math.max(-speed,Math.min(speed,p.vx));else if(p.ground)p.vx*=Math.exp(-12*dt)}else if(p.ground)p.vx*=Math.exp(-10*dt);p.vy+=1000*dt;const solids=bridgeOpen?[...platforms,bridge]:platforms;const oldX=p.x;p.x+=p.vx*dt;for(const s of solids){if(overlap(p,s)){p.x=p.vx>0?s.x-p.w:s.x+s.w;p.vx=0}}p.x=Math.max(0,Math.min(world-p.w,p.x));const oldY=p.y;p.y+=p.vy*dt;p.ground=false;for(const s of solids){if(overlap(p,s)){if(p.vy>=0&&oldY+p.h<=s.y+2){p.y=s.y-p.h;p.ground=true;p.vy=0}else if(p.vy<0&&oldY>=s.y+s.h-2){p.y=s.y+s.h;p.vy=0}else{p.x=oldX}}}}
function update(dt){time+=dt;if(won)return;mergeDelay=Math.max(0,mergeDelay-dt);if(joined){if(pointer)angle=Math.atan2(pointer.y-(head.y+14),pointer.x+camera-(head.x+14));if(keys.has('KeyQ')||keys.has('KeyE')){pointer=null;angle+=(keys.has('KeyE')?1:-1)*dt*1.8}if(charging){spaceHeld+=dt;charge=Math.min(1,Math.max(0,spaceHeld-HOLD_THRESHOLD)/1.4);}physics(body,dt,true);head.x=body.x+1;head.y=body.y-28;head.vx=body.vx;head.vy=body.vy}else{physics(body,dt,active==='body');physics(head,dt,active==='head');if(mergeDelay===0&&overlap({x:body.x-5,y:body.y-30,w:body.w+10,h:body.h+30},head)){joined=true;head.x=body.x+1;head.y=body.y-28;say('合体成功！可以再次蓄力发射。')}}
if(!bridgeOpen&&[body,head].some(p=>p.ground&&p.x+p.w>switchPad.x&&p.x<switchPad.x+switchPad.w&&Math.abs(p.y+p.h-switchPad.y)<3)){bridgeOpen=true;say('桥梁已打开！继续向右，身体也能通过。')}
for(const s of stars)if(!s.got&&[head,body].some(p=>overlap(p,{x:s.x-13,y:s.y-13,w:26,h:26}))){s.got=true;for(let i=0;i<14;i++)particles.push({x:s.x,y:s.y,vx:(Math.random()-.5)*140,vy:-Math.random()*180,life:.7});say('星星收集成功！ '+stars.filter(s=>s.got).length+' / 3')}
if(joined&&body.x>1000&&!checkpoint){checkpoint=1;say('检查点已点亮，按 R 从这里再出发。')}
if(body.y>H+160||head.y>H+160){reset(false);return}if(body.x>2220&&joined){if(stars.every(s=>s.got)){won=true;say('通关啦！头和身体，一起到家。点击重新开始再玩一次。')}else say('小屋需要三颗星星，再回去找找吧。')}
const target=Math.max(0,Math.min(world-W,controlled().x-W*.38));camera+=(target-camera)*Math.min(1,dt*5);particles=particles.filter(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=250*dt;return p.life>0})}
function rect(x,y,w,h,c,r=0){ctx.fillStyle=c;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function text(s,x,y,size=14,color='#bed3ce'){ctx.fillStyle=color;ctx.font=`${size}px system-ui`;ctx.fillText(s,x,y)}
function star(x,y,r,color){ctx.fillStyle=color;ctx.beginPath();for(let i=0;i<10;i++){let a=-Math.PI/2+i*Math.PI/5,rr=i%2?r*.45:r;ctx.lineTo(x+Math.cos(a)*rr,y+Math.sin(a)*rr)}ctx.closePath();ctx.fill()}
function cat(p,isHead){const selected=joined||controlled()===p;if(selected){ctx.strokeStyle='#d6f6d7';ctx.lineWidth=2;ctx.beginPath();ctx.roundRect(p.x-5,p.y-5,p.w+10,p.h+10,9);ctx.stroke()}if(isHead){rect(p.x,p.y,p.w,p.h,'#f7d69c',8);ctx.fillStyle='#f7d69c';ctx.beginPath();ctx.moveTo(p.x,p.y+9);ctx.lineTo(p.x+2,p.y-8);ctx.lineTo(p.x+12,p.y+3);ctx.moveTo(p.x+17,p.y+3);ctx.lineTo(p.x+26,p.y-8);ctx.lineTo(p.x+28,p.y+9);ctx.fill();rect(p.x+6,p.y+10,3,4,'#263e42');rect(p.x+19,p.y+10,3,4,'#263e42');text('ω',p.x+9,p.y+24,12,'#75563e')}else{rect(p.x,p.y,p.w,p.h,'#d69771',7);rect(p.x+5,p.y+27,7,7,'#f7d69c',3);rect(p.x+19,p.y+27,7,7,'#f7d69c',3);ctx.strokeStyle='#d69771';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(p.x+28,p.y+20);ctx.quadraticCurveTo(p.x+45,p.y+20,p.x+39,p.y+9);ctx.stroke()}}
function draw(){ctx.clearRect(0,0,W,H);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#203f50');g.addColorStop(1,'#4c7775');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#e9dcab';ctx.beginPath();ctx.arc(910-camera*.07,95,34,0,Math.PI*2);ctx.fill();for(let i=0;i<35;i++){ctx.fillStyle='#bed9cb55';ctx.fillRect((i*137+37-camera*.12)%W,40+(i*67)%240,2,2)}for(let layer=0;layer<2;layer++){ctx.fillStyle=layer?'#2a565d':'#315b66';ctx.beginPath();ctx.moveTo(0,H);for(let x=-100;x<W+100;x+=60)ctx.lineTo(x,340+layer*90+Math.sin((x+camera*(.12+layer*.1))/160)*40);ctx.lineTo(W,H);ctx.fill()}
ctx.save();ctx.translate(-camera,0);for(const s of platforms){rect(s.x,s.y,s.w,s.h,'#253d43',8);rect(s.x,s.y,s.w,8,'#9bbd96',4);for(let x=s.x+20;x<s.x+s.w;x+=45)rect(x,s.y+24,16,3,'#3b5556',2)}if(bridgeOpen){rect(bridge.x,bridge.y,bridge.w,14,'#c1a681',4);for(let x=bridge.x;x<bridge.x+bridge.w;x+=24)rect(x,bridge.y,3,14,'#806d5b')}else{ctx.setLineDash([8,8]);ctx.strokeStyle='#b7d5be55';ctx.strokeRect(bridge.x,bridge.y,bridge.w,14);ctx.setLineDash([])}rect(switchPad.x,switchPad.y-6,switchPad.w,6,bridgeOpen?'#ffe29c':'#86e0c5',3);text(bridgeOpen?'桥梁已开启':'踩这里打开桥梁',760,350,14);text('蓄力抛头 ↗',185,445,18);text('切换身体，跟上来 →',1020,447,16);text('头部可以跳得更高',1790,300,14);
ctx.strokeStyle=checkpoint?'#ffe4a1':'#b7cdc5';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(1060,500);ctx.lineTo(1060,455);ctx.stroke();rect(1060,455,25,14,checkpoint?'#ffe4a1':'#819c99',2);for(const s of stars)if(!s.got)star(s.x,s.y+Math.sin(time*3)*4,13,'#ffe3a0');rect(2200,420,100,70,'#debd91',6);ctx.fillStyle='#956e66';ctx.beginPath();ctx.moveTo(2187,423);ctx.lineTo(2250,376);ctx.lineTo(2313,423);ctx.fill();rect(2238,449,24,41,'#4c6663',4);rect(2213,437,15,15,'#ffe9aa',3);text('一起回家',2210,360,16);if(!joined){ctx.strokeStyle='#e4ddbb44';ctx.setLineDash([4,7]);ctx.beginPath();ctx.moveTo(body.x+15,body.y+12);ctx.lineTo(head.x+14,head.y+14);ctx.stroke();ctx.setLineDash([])}cat(body,false);cat(head,true);
if(joined&&!won){let x=head.x+14,y=head.y+14;const v=380+charge*620;ctx.fillStyle='#ffedb6';for(let t=.05;t<.8;t+=.06){ctx.globalAlpha=1-t;ctx.beginPath();ctx.arc(x+Math.cos(angle)*v*t,y+Math.sin(angle)*v*t+500*t*t,2.5,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;ctx.strokeStyle='#fff0b9';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+Math.cos(angle)*55,y+Math.sin(angle)*55);ctx.stroke();if(charging){rect(body.x-15,head.y-28,60,7,'#15313b',4);rect(body.x-15,head.y-28,60*charge,7,'#ffe2a0',4)}}for(const p of particles)star(p.x,p.y,4,'#ffe5a8');ctx.restore();rect(22,20,240,69,'#14313ad9',12);text('星星 '+stars.filter(s=>s.got).length+' / 3     '+(joined?'合体':active==='head'?'控制：头部':'控制：身体'),38,46,16,'#f1edda');text('角度 '+Math.round(-angle*180/Math.PI)+'°  ·  力度 '+Math.round(charge*100)+'%',38,72,12);if(won){rect(320,210,460,145,'#122e3aee',18);text('冒险完成，猫猫到家！',370,266,27,'#ffe2a0');text('三颗星星，一场两部分的旅行。',394,302,16);text('点击右上角「重新开始」再来一次',383,331,14)}}
function frame(now){const elapsed=last?Math.min((now-last)/1000,.05):0;last=now;let left=elapsed;while(left>0){const dt=Math.min(left,1/120);update(dt);left-=dt}draw();requestAnimationFrame(frame)}requestAnimationFrame(frame);
